config/routes.rb
ComplexNestedForm::Application.routes.draw do
  resources :sub_units

  resources :organizations

  root :to => 'organizations#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :sub_units_attributes
  has_many :sub_units, dependent: :destroy
  accepts_nested_attributes_for :sub_units, allow_destroy: true, reject_if: proc { |a| a["name"].blank? }
  validates_presence_of :name
end

app/models/sub_unit.rb
class SubUnit < ActiveRecord::Base
  attr_accessible :name, :organization_id
  belongs_to :organization

  validates :name,
            presence: true,
            uniqueness: { scope: :organization_id }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def new
    @organization = Organization.new
    @organization.sub_units.build
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def create
    @organization = Organization.new(params[:organization])

    if @organization.save
      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new
    end
  end

  def update
    @organization = Organization.find(params[:id])

    if @organization.update_attributes(params[:organization])
      redirect_to @organization, notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    redirect_to organizations_url
  end
end

app/controllers/sub_units_controller.rb
class SubUnitsController < ApplicationController
  # GET /sub_units
  # GET /sub_units.json
  def index
    @sub_units = SubUnit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sub_units }
    end
  end

  # GET /sub_units/1
  # GET /sub_units/1.json
  def show
    @sub_unit = SubUnit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_unit }
    end
  end

  # GET /sub_units/new
  # GET /sub_units/new.json
  def new
    @sub_unit = SubUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_unit }
    end
  end

  # GET /sub_units/1/edit
  def edit
    @sub_unit = SubUnit.find(params[:id])
  end

  # POST /sub_units
  # POST /sub_units.json
  def create
    @sub_unit = SubUnit.new(params[:sub_unit])

    respond_to do |format|
      if @sub_unit.save
        format.html { redirect_to @sub_unit, notice: 'Sub unit was successfully created.' }
        format.json { render json: @sub_unit, status: :created, location: @sub_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sub_units/1
  # PUT /sub_units/1.json
  def update
    @sub_unit = SubUnit.find(params[:id])

    respond_to do |format|
      if @sub_unit.update_attributes(params[:sub_unit])
        format.html { redirect_to @sub_unit, notice: 'Sub unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_units/1
  # DELETE /sub_units/1.json
  def destroy
    @sub_unit = SubUnit.find(params[:id])
    @sub_unit.destroy

    respond_to do |format|
      format.html { redirect_to sub_units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sub_units_helper.rb
module SubUnitsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "ComplexNestedForm"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") ComplexNestedForm

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to 'Organizations', organizations_path
              %li= link_to 'Sub Units', sub_units_path
        .span9
          = yield

      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/organizations/_form.html.haml
= form_for @organization, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), organizations_path, :class => 'btn'

app/views/organizations/_sub_unit_fields.html.haml
.control-group
  = f.label :name, class: 'control-label'
  .controls.sub-unit
    = f.text_field :name, class: 'input-mini'
    = f.hidden_field :_destroy
    = link_to "remove", '#', class: 'btn btn-warning btn-mini remove-sub-unit-button'

app/views/organizations/edit.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/organizations/index.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.id, organization_path(organization)
        %td= organization.name
        %td=l organization.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_organization_path(organization), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), organization_path(organization), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_organization_path, :class => 'btn btn-primary'

app/views/organizations/new.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")

= form_for @organization, :html => { :class => 'form-horizontal' } do |f|
  .row-fluid
    .span6
      .well
        %h2 Organization Info
        .control-group
          = f.label :name, :class => 'control-label'
          .controls
            = f.text_field :name, :class => 'text_field input-medium'

    .span6
      .well.sub-units
        %h2 SubUnit Info
        = f.fields_for :sub_units do |f_sub|
          = render 'sub_unit_fields', f: f_sub

        .control-group.add-sub-unit
          .controls
            = link_to 'add a SubUnit', '#', class: 'btn btn-primary add-sub-unit-button'

        #new-sub-unit-fields.hidden
          = f.fields_for :sub_units, SubUnit.new, child_index: 'new_sub_unit' do |f_sub|
            = render 'sub_unit_fields', f: f_sub

    .span12
      .form-actions
        = link_to 'Create Organization', '#', class: 'btn btn-primary create-organization-button'
        = link_to t('.cancel', :default => t("helpers.links.cancel")), organizations_path, :class => 'btn'

app/views/organizations/show.html.haml
- model_class = Organization
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @organization.name

%p
  %strong SubUnits
  %br
  = @organization.sub_units.map(&:name).join(', ')

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), organizations_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_organization_path(@organization), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), organization_path(@organization), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/sub_units/_form.html.haml
= form_for @sub_unit, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :organization_id, :class => 'control-label'
    .controls
      = f.number_field :organization_id, :class => 'number_field'
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), sub_units_path, :class => 'btn'

app/views/sub_units/edit.html.haml
- model_class = SubUnit
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/sub_units/index.html.haml
- model_class = SubUnit
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:organization_id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @sub_units.each do |sub_unit|
      %tr
        %td= link_to sub_unit.id, sub_unit_path(sub_unit)
        %td= sub_unit.organization_id
        %td= sub_unit.name
        %td=l sub_unit.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_sub_unit_path(sub_unit), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), sub_unit_path(sub_unit), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_sub_unit_path, :class => 'btn btn-primary'

app/views/sub_units/new.html.haml
- model_class = SubUnit
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/sub_units/show.html.haml
- model_class = SubUnit
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:organization_id) + ':'
  %br
  = @sub_unit.organization_id
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @sub_unit.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), sub_units_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_sub_unit_path(@sub_unit), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), sub_unit_path(@sub_unit), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'